interface IPageSeoOptions {
    title: () => string;
    description: () => string;
    // Route path without the locale prefix, e.g. '/education-materials'
    path: string;
    // Absolute path of a 1200x630 JPEG under /public
    image: () => string;
    imageAlt: () => string;
}

// Title, description, Open Graph and Twitter tags for a page. Canonical,
// hreflang and og:locale come from useLocaleHead in app.vue.
export const usePageSeo = (options: IPageSeoOptions) => {
    const localePath = useLocalePath();

    // Same form as the canonical URL generated by @nuxtjs/i18n (no trailing slash)
    const pageUrl = computed(
        () => `${SITE_URL}${localePath(options.path).replace(/\/$/, '')}`
    );
    const imageUrl = computed(() => `${SITE_URL}${options.image()}`);

    useSeoMeta({
        title: options.title,
        description: options.description,
        ogTitle: options.title,
        ogDescription: options.description,
        ogUrl: () => pageUrl.value,
        ogImage: () => imageUrl.value,
        ogImageWidth: 1200,
        ogImageHeight: 630,
        ogImageType: 'image/jpeg',
        ogImageAlt: options.imageAlt,
        twitterTitle: options.title,
        twitterDescription: options.description,
        twitterImage: () => imageUrl.value,
        twitterImageAlt: options.imageAlt,
    });

    return { pageUrl, imageUrl };
};
